export const SET_CHAT_STATUS = 'SET_CHAT_STATUS';
export type SET_CHAT_STATUS = typeof SET_CHAT_STATUS;

export const SET_MESSAGES = 'SET_MESSAGES';
export type SET_MESSAGES = typeof SET_MESSAGES;

export const CLEAR_MESSAGES = 'CLEAR_MESSAGES';
export type CLEAR_MESSAGES = typeof CLEAR_MESSAGES;

export const SET_WEBSOCKET = 'SET_WEBSOCKET';
export type SET_WEBSOCKET = typeof SET_WEBSOCKET;

export const UPDATE_AUTH_STATUS = 'UPDATE_AUTH_STATUS';
export type UPDATE_AUTH_STATUS = typeof UPDATE_AUTH_STATUS;

export const SET_USERNAME = 'SET_USERNAME';
export type SET_USERNAME = typeof SET_USERNAME;

export const ADD_OFFLINE_MESSAGE = 'ADD_OFFLINE_MESSAGE';
export type ADD_OFFLINE_MESSAGE = typeof ADD_OFFLINE_MESSAGE;

export const REMOVE_OFFLINE_MESSAGES = 'REMOVE_OFFLINE_MESSAGES';
export type REMOVE_OFFLINE_MESSAGES = typeof REMOVE_OFFLINE_MESSAGES;

export const SET_RECONNECT_STATUS = 'SET_RECONNECT_STATUS';
export type SET_RECONNECT_STATUS = typeof SET_RECONNECT_STATUS;

export const UPDATE_NOTIFICATIONS_STATUS = 'UPDATE_NOTIFICATIONS_STATUS';
export type UPDATE_NOTIFICATIONS_STATUS = typeof UPDATE_NOTIFICATIONS_STATUS;

export const UPDATE_TAB_STATUS = 'UPDATE_TAB_STATUS';
export type UPDATE_TAB_STATUS = typeof UPDATE_TAB_STATUS;

export const SHOW_SETTINGS_MODAL_WINDOW = 'SHOW_SETTINGS_MODAL_WINDOW';
export type SHOW_SETTINGS_MODAL_WINDOW = typeof SHOW_SETTINGS_MODAL_WINDOW;

export const UPDATE_BACKGROUND_ID = 'UPDATE_BACKGROUND_ID';
export type UPDATE_BACKGROUND_ID = typeof UPDATE_BACKGROUND_ID;
